language: android
jdk:
  - openjdk11
sudo: false
android:
  components:
  - tools
  - platform-tools
  - build-tools-30.0.3
  - android-30
  licenses:
  - android-sdk-license-.+
before_install:
  - yes | sdkmanager "platforms;android-30"
script:
- "./gradlew assembleDebug --daemon"
